---
title: "Project 1 - Modeling Results"
author: "Andrew Kerr"
date: "2023-11-18"
output: html_document
---

```{r setup, include=FALSE, include=FALSE, warning=FALSE}
library(tidyverse)
library(lme4)
load(url("http://www.rossmanchance.com/iscam3/ISCAM.RData"))
```

```{r}
df_TFT <- read_csv(here::here('Project', 'TFT_data.csv'))
head(df_TFT, 5)
```

# Data Manipulation



```{r}
# Set the correct columns to factors
df_TFT$is_challenger <- as.logical(df_TFT$is_challenger == "Challenger")
# df_TFT$is_challenger <- as.logical(df_TFT$is_challenger, levels=c(TRUE, FALSE), labels=c(1, 0))
# df_TFT$is_challenger <- factor(df_TFT$is_challenger, levels=c(TRUE, FALSE), labels=c(1, 0))
df_TFT$level <- factor(df_TFT$level, levels=c('1', '2', '3', '4', '5', '6', '7', '8', '9', '10'))
df_TFT$placement <- factor(df_TFT$placement, levels=c('1', '2', '3', '4', '5', '6', '7', '8'))
df_TFT$n_legend <- factor(df_TFT$n_legend, levels=c('0', '1', '2', '3'))

#All quantitative variables are grand-mean centered
centered_TFT <- df_TFT %>%
  select(-is_challenger, -match_id, -level, -placement, -n_legend) %>%
  mutate_all(~ . - mean(., na.rm = TRUE))

df_TFT <- df_TFT %>%
  select(is_challenger, match_id, level, placement, n_legend) %>%
  bind_cols(centered_TFT)
```


# Exploring the variability in the response variable across the Level-2 units

```{r}
boxplot(is_challenger ~ match_id, data = df_TFT, main = 'Variability in Response Across Level-2 Units')
```

```{r}
model1 <- lm(is_challenger ~ match_id, data=df_TFT)
summary(model1)
```


```{r}
model1 <- glm(is_challenger ~ match_id, family = binomial, data=df_TFT[1:1000,])
summary(model1)
```

```{r}
model2 <- glmer(is_challenger ~ (1 | match_id), family = "binomial", data = df_TFT)
summary(model2)
```







